rust_compiler:
  - rust
rust_compiler_version:
  - 1.76.0
# use {{ compiler('rust-gnu') }} when requiring a build using the m2w64-toolchain
rust_gnu_compiler:             # [win]
  - rust-gnu                   # [win]
rust_gnu_compiler_version:     # [win]
  - 1.76.0                     # [win]
MACOSX_DEPLOYMENT_TARGET:   # [osx and x86_64]
  - "10.12"                 # [osx and x86_64]
rust_compiler_version:
  - 1.76.0
CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.12.sdk    # [osx and x86_64]