{% set name = "y-py" %}
{% set version = "0.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/y/y_py/y_py-{{ version }}.tar.gz
  sha256: 46836169f7dc2957df8513cfe4bc2009175b3a473e630af421a8e75ee1c48f98

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=0.13,<0.14                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - maturin =0.13.7
    - pip
    - python
    - wheel 
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - y_py

about:
  home: https://github.com/y-crdt/ypy
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Python bindings for the Rust port of Yjs
  description: Ypy is a Python binding for Y-CRDT. It provides distributed data types that enable real-time collaboration between devices. Ypy can sync data with any other platform that has a Y-CRDT binding, allowing for seamless cross-domain communication. 
  dev_url: https://github.com/y-crdt/ypy
  doc_url: https://ypy.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - davidbrochart
    - Waidhoferj
    - fcollonval
