{% set name = "y-py" %}
{% set version = "0.4.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/y/y_py/y_py-{{ version }}.tar.gz
  sha256: b0130cae26ad36d78abeb2440cafa03af599852bafd89145247ff486150317f1

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - maturin >=0.12.4
    - pip
    - python
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - y_py

about:
  home: https://github.com/y-crdt/ypy
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Python bindings for the Rust port of Yjs
  dev_url: https://github.com/y-crdt/ypy

extra:
  recipe-maintainers:
    - davidbrochart
    - Waidhoferj
