{% set name = "y-py" %}
{% set version = "0.6.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/y/y_py/y_py-{{ version }}.tar.gz
  sha256: 4757a82a50406a0b3a333aa0122019a331bd6f16e49fed67dca423f928b3fd4d

build:
number: 0
  skip: True # [s390x]
  script:
    - {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  ignore_run_exports:
    - python

requirements:
  build:
    - python
    - maturin >=1.2.3,<2
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - maturin 1.3.1
    - pip
    - python
  run:
    # this is needed otherwise import y_py in tests fails with ModuleNotFoundError
    - python

test:
  source_files:
    # There doesn't seem to be a smaller subset of the directory that works on windows.
    - tests # [ not win ]
    - .     # [ win ]
  imports:
    - y_py
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -m pytest -vv

about:
  home: https://github.com/y-crdt/ypy
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Python bindings for the Rust port of Yjs
  description: Ypy is a Python binding for Y-CRDT. It provides distributed data types that enable real-time collaboration between devices. Ypy can sync data with any other platform that has a Y-CRDT binding, allowing for seamless cross-domain communication.
  dev_url: https://github.com/y-crdt/ypy
  doc_url: https://ypy.readthedocs.io

extra:
  recipe-maintainers:
    - davidbrochart
    - Waidhoferj
    - fcollonval
